on: [push]
steps:
    - uses: actions/checkout@v2
    - name: Import terraform property
      uses: deepakjd2004/akamai-import-terraform-property-github-action
      env:
        EDGERC: ${{ secrets.EDGERC }}
      with:
        propertyName : 'dj-config-rapid-dj' # replace with the name of your domain
