name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run thisworkflow manually from the Actions tabs
  workflow_dispatch:
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Import terraform property
        uses: deepakjd2004/akamai-import-terraform-property-github-action@v1.76
        env:
          EDGERC: ${{ secrets.EDGERC }}
          SWITCH_KEY: ${{ secrets.AKAMAI_AS_ACCOUNTSWITCHKEY }}
        with:
          propertyName : 'Devops-Training' # replace with the name of your domain
